name: samurai
services:
  postgres:
    container_name: samurai_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=samurai'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=samurai'
    volumes:
      - C:\Users\aitel\OneDrive\Documents\pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local